version = "0.1.0"
algorithm = "sha384"

[data]
"aa.toml" = '''
[token_configs]
[token_configs.kbs]
url = "http://130.233.195.35:31401"
'''

"cdh.toml" = '''
[kbc]
name = "cc_kbc"
url = "http://130.233.195.35:31401"

[image]
extra_root_certificates = ["""
-----BEGIN CERTIFICATE-----
MIIDCzCCAfOgAwIBAgIUFxx7pr5NuFQZRC0haZ8zWudTEt0wDQYJKoZIhvcNAQEL
BQAwFTETMBEGA1UEAwwKQ29Db1Jvb3RDQTAeFw0yNjA0MjExNTMxMzZaFw0yNzA0
MjExNTMxMzZaMBUxEzARBgNVBAMMCkNvQ29Sb290Q0EwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQCbUgIiEKIKcDcb8wi2Qt7kLbPRdhGDpdRQ1SujdBHJ
MCCsrZBRcwk79CCz4t9e5C3cXPNixcKo5a8qa6dmbt5BObUtHuiSx81JhAwOYIIG
JSfzXXihQAwqkqbuf5dy2gO94gba2efO/vMT0JX6sn3p6nBW0l3HVa1rTtxBKCqA
xmmYBnsL6XJJANfCImvMngR1xFnNWl6QKPWyvkN3+5Z+RoqfVGlZig1Q5LKcYRoy
T+31sw6IuxDmZ4C7XzbZ1ZRZQMn5j1Z0Z1vscBVNnjSrzXTYYSmPhSJc7+kjS0HS
1f4I9HnW8z1Xjb8dEHhH+A4Q/l5fElA3aOS7JQC7S3CTAgMBAAGjUzBRMB0GA1Ud
DgQWBBT/Y8l0KXxh6abvFmTNirnyk5k6rTAfBgNVHSMEGDAWgBT/Y8l0KXxh6abv
FmTNirnyk5k6rTAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCE
cH1Kv0UBXz26Yj95eJSXAoVqtoRRFqNLh3+2DfNuzAMIDKHbp7IgIlJ+de2+9l2y
StXMFI+ZGjDG3BJq9XXxKsCJHgiGg2A+a1ytz+trqkvemWp66UYn72zo+K7kLr6s
ZVOZaKwiRMlAlQelFyiRAeFUeADH0J0JPDQWFzIC5DLADliqi4Gsp2d55cR4Q2NH
NwAMutiEcQJF1mARenJ0w/0+Vxg7BqjWOfcgMPzv68lahaeYNF+fHsy6Xzu2R1+y
XTG1EIs9ZmtJ1ilr2A+8NiwD6d0FryhtsJ84cBO4ETyo7Ji7Cid22urtFwciZ4Xz
vGExNYbwiAfZ6U5VaZAQ
-----END CERTIFICATE-----
"""]
'''
