#!/usr/bin/env python3
"""Generate one initdata policy file per store-demo pod.

Each pod runs under its own policy that admits only the shared infrastructure
containers (pause, iptables-init, attestation sidecar, Envoy) and that pod's
single application image. A pod therefore cannot be started with any image
other than the one intended for it, and each pod carries a distinct MRCONFIGID
that the verifier checks against the expected policy for that pod.

Digests and command args are resolved from the local registry at generation
time via ``docker inspect`` (not hardcoded), so re-running this after an image
rebuild picks up the new digests automatically. The app images must be present
locally (they are, right after mirroring/pushing them).
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REGISTRY = "130.233.195.35:5000"
OUT_DIR = Path(__file__).parent / "store"

# Infrastructure images shared by every pod (stable, same as the base
# deployment). These are pinned rather than resolved because they are built
# separately and do not change per store-app rebuild.
IPTABLES_DIGEST = "sha256:a33779d0e8e49bd4a65debae3b6833da4d090a2be0d24064014159889be94e67"
PEER_DIGEST     = "sha256:9641c0adcdf686cfab28881d06f9257215046488c3a34b7c6fcc77c55a96a238"
ENVOY_DIGEST    = "sha256:e5e530a61bb1ce655fa4a8ec567497112fcad296cb40ef00382ac575e8bd5e64"

# Per-pod application image: pod -> (repo, tag, args_override).
# args_override mirrors any `args:` set in the pod spec (which replaces the
# image CMD). None means the image CMD is used unchanged.
APPS: dict[str, tuple[str, str, list[str] | None]] = {
    "documentdb":       ("documentdb-local", "pg17-0.112.0",
                         ["--username", "username", "--password", "password"]),
    "rabbitmq":         ("rabbitmq", "4.3.2-management-alpine", None),
    "order-service":    ("order-service", "2.2.0", None),
    "makeline-service": ("makeline-service", "2.2.0", None),
    "product-service":  ("product-service", "2.2.0", None),
    "store-front":      ("store-front", "2.2.0", None),
    "store-admin":      ("store-admin", "2.2.0", None),
}

CDH_CERT = """-----BEGIN CERTIFICATE-----
MIIDCzCCAfOgAwIBAgIUFxx7pr5NuFQZRC0haZ8zWudTEt0wDQYJKoZIhvcNAQEL
BQAwFTETMBEGA1UEAwwKQ29Db1Jvb3RDQTAeFw0yNjA0MjExNTMxMzZaFw0yNzA0
MjExNTMxMzZaMBUxEzARBgNVBAMMCkNvQ29Sb290Q0EwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQCbUgIiEKIKcDcb8wi2Qt7kLbPRdhGDpdRQ1SujdBHJ
MCCsrZBRcwk79CCz4t9e5C3cXPNixcKo5a8qa6dmbt5BObUtHuiSx81JhAwOYIIG
JSfzXXihQAwqkqbuf5dy2gO94gba2efO/vMT0JX6sn3p6nBW0l3HVa1rTtxBKCqA
xmmYBnsL6XJJANfCImvMngR1xFnNWl6QKPWyvkN3+5Z+RoqfVGlZig1Q5LKcYRoy
T+31sw6IuxDmZ4C7XzbZ1ZRZQMn5j1Z0Z1vscBVNnjSrzXTYYSmPhSJc7+kjS0HS
1f4I9HnW8z1Xjb8dEHhH+A4Q/l5fElA3aOS7JQC7S3CTAgMBAAGjUzBRMB0GA1Ud
DgQWBBT/Y8l0KXxh6abvFmTNirnyk5k6rTAfBgNVHSMEGDAWgBT/Y8l0KXxh6abv
FmTNirnyk5k6rTAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCE
cH1Kv0UBXz26Yj95eJSXAoVqtoRRFqNLh3+2DfNuzAMIDKHbp7IgIlJ+de2+9l2y
StXMFI+ZGjDG3BJq9XXxKsCJHgiGg2A+a1ytz+trqkvemWp66UYn72zo+K7kLr6s
ZVOZaKwiRMlAlQelFyiRAeFUeADH0J0JPDQWFzIC5DLADliqi4Gsp2d55cR4Q2NH
NwAMutiEcQJF1mARenJ0w/0+Vxg7BqjWOfcgMPzv68lahaeYNF+fHsy6Xzu2R1+y
XTG1EIs9ZmtJ1ilr2A+8NiwD6d0FryhtsJ84cBO4ETyo7Ji7Cid22urtFwciZ4Xz
vGExNYbwiAfZ6U5VaZAQ
-----END CERTIFICATE-----"""


def _inspect(ref: str, fmt: str) -> str:
    out = subprocess.run(["docker", "inspect", "--format", fmt, ref],
                         capture_output=True, text=True)
    if out.returncode != 0:
        raise RuntimeError(f"docker inspect {ref} failed: {out.stderr.strip()}")
    return out.stdout.strip()


def resolve(repo: str, tag: str, override: list[str] | None) -> tuple[str, list[str]]:
    """Return (digest, expected_oci_args) for the local image REGISTRY/repo:tag."""
    ref = f"{REGISTRY}/{repo}:{tag}"
    repo_digests = _inspect(ref, "{{range .RepoDigests}}{{println .}}{{end}}").splitlines()
    prefix = f"{REGISTRY}/{repo}@"
    digest = next((rd.split("@", 1)[1] for rd in repo_digests if rd.startswith(prefix)), None)
    if digest is None:
        raise RuntimeError(f"{ref} has no {REGISTRY} repo digest — is it pushed?")
    entrypoint = json.loads(_inspect(ref, "{{json .Config.Entrypoint}}")) or []
    cmd = json.loads(_inspect(ref, "{{json .Config.Cmd}}")) or []
    args = entrypoint + (override if override is not None else cmd)
    return digest, args


def build_policy(pod: str, repo: str, digest: str, args: list[str]) -> str:
    return f'''version = "0.1.0"
algorithm = "sha384"

# Policy for pod '{pod}'. Admits the shared infrastructure containers and only
# this pod's application image ({repo}). Generated by generate_store_policies.py.

[data]
"policy.rego" = \'\'\'
package agent_policy
import rego.v1

# Allow management operations
default CreateSandboxRequest := true
default DestroySandboxRequest := true
default GuestDetailsRequest := true
default StartContainerRequest := true
default StatsContainerRequest := true

# Process-level operations (permissive in the prototype; restrict for production)
default ExecProcessRequest := true
default SignalProcessRequest := true
default WaitProcessRequest := true
default GetOOMEventRequest := true

# Container creation is denied unless explicitly allowed below
default CreateContainerRequest := false
default UpdateInterfaceRequest := true
default UpdateRoutesRequest := true
default CopyFileRequest := true
default ReadStreamRequest := true #allow logs

# Sandbox pause container.
CreateContainerRequest if {{
	input.OCI.Process.Args == ["/pause"]
}}

# iptables init container.
CreateContainerRequest if {{
	some storage in input.storages
	storage.source == "{REGISTRY}/iptables-init@{IPTABLES_DIGEST}"
	input.OCI.Process.Args == ["/iptables-redirect.sh"]
}}

# Attestation sidecar: ./peer --id=<pod-id>.
CreateContainerRequest if {{
	some storage in input.storages
	storage.source == "{REGISTRY}/p2p-attestation@{PEER_DIGEST}"
	count(input.OCI.Process.Args) == 2
	input.OCI.Process.Args[0] == "./peer"
	regex.match(`^--id=[a-z0-9]+-[0-9]+$`, input.OCI.Process.Args[1])
}}

# Envoy: bash with the attestation-gate poll loop (matched structurally).
CreateContainerRequest if {{
	some storage in input.storages
	storage.source == "{REGISTRY}/envoy@{ENVOY_DIGEST}"
	count(input.OCI.Process.Args) == 3
	input.OCI.Process.Args[0] == "/bin/bash"
	input.OCI.Process.Args[1] == "-c"
	contains(input.OCI.Process.Args[2], "/.well-known/attestation")
	contains(input.OCI.Process.Args[2], "exec envoy -c /etc/envoy/envoy.yaml")
}}

# Application image for this pod.
CreateContainerRequest if {{
	some storage in input.storages
	storage.source == "{REGISTRY}/{repo}@{digest}"
	input.OCI.Process.Args == {json.dumps(args)}
}}
\'\'\'

"aa.toml" = \'\'\'
[token_configs]
[token_configs.kbs]
url = "http://130.233.195.35:31401"
\'\'\'

"cdh.toml" = \'\'\'
[kbc]
name = "cc_kbc"
url = "http://130.233.195.35:31401"

[image]
extra_root_certificates = ["""
{CDH_CERT}
"""]
\'\'\'
'''


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for pod, (repo, tag, override) in APPS.items():
        try:
            digest, args = resolve(repo, tag, override)
        except RuntimeError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 1
        path = OUT_DIR / f"initdata_{pod}.toml"
        path.write_text(build_policy(pod, repo, digest, args))
        print(f"Wrote {path.name}: {repo}@{digest[:19]}...  args={args}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
