#!/usr/bin/env python3
"""Generate the per-service Envoy ConfigMaps from a single template.

Every service's Envoy config is identical except for the local_app port (the
port its application container listens on). Rather than repeat the full config
per service in the deployment manifest, the two base configs (HTTP and raw-TCP)
live once in envoy-config.templates.yaml with a {{APP_PORT}} placeholder, and
this script stamps out one ConfigMap per service into envoy-configs.yaml.

Apply the result alongside the deployment manifest:
    kubectl apply -f envoy-configs.yaml -f aks-store-all-in-one-confidential.yaml
"""

from __future__ import annotations

import argparse
import pathlib
import sys

HERE = pathlib.Path(__file__).parent

# service -> (app port, template kind). Must match the app containerPort and the
# inbound protocol of each workload in the deployment manifest.
SERVICES: dict[str, tuple[int, str]] = {
    "documentdb":       (10260, "tcp"),
    "rabbitmq":         (5672,  "tcp"),
    "order-service":    (3000,  "http"),
    "makeline-service": (3001,  "http"),
    "product-service":  (3002,  "http"),
    "store-front":      (8080,  "http"),
    "store-admin":      (8081,  "http"),
}


def load_templates(templates_path: pathlib.Path) -> dict[str, str]:
    """Read the two block-scalar bodies (http, tcp) from the templates file."""
    import yaml
    data = yaml.safe_load(templates_path.read_text())
    if not {"http", "tcp"} <= data.keys():
        raise ValueError(f"{templates_path} must define 'http' and 'tcp' bodies")
    return data


def configmap(cm_name: str, port: int, kind: str, templates: dict[str, str]) -> str:
    body = templates[kind].replace("{{APP_PORT}}", str(port))
    indented = "\n".join(("    " + l if l else l) for l in body.splitlines())
    return (f"apiVersion: v1\nkind: ConfigMap\nmetadata:\n"
            f"  name: {cm_name}\ndata:\n  envoy.yaml: |\n{indented}\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--templates", type=pathlib.Path, default=HERE / "envoy-config.templates.yaml",
                    help="templates file with 'http'/'tcp' bodies (default: envoy-config.templates.yaml)")
    ap.add_argument("--output", type=pathlib.Path, default=HERE / "envoy-configs.yaml",
                    help="ConfigMap output file (default: envoy-configs.yaml)")
    ap.add_argument("--prefix", default="envoy-config-",
                    help="ConfigMap name prefix (default: envoy-config-)")
    args = ap.parse_args()

    try:
        templates = load_templates(args.templates)
    except (FileNotFoundError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    names = {n: f"{args.prefix}{n}" for n in SERVICES}
    blocks = [configmap(names[n], port, kind, templates) for n, (port, kind) in SERVICES.items()]
    args.output.write_text(f"# Generated by generate_envoy_configs.py --templates {args.templates.name} — do not edit by hand.\n"
                           f"# Edit {args.templates.name} or the SERVICES table instead.\n---\n"
                           + "\n---\n".join(b.rstrip("\n") for b in blocks) + "\n")
    print(f"Wrote {args.output.name}: {', '.join(names.values())}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
